name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdk:
    name: "Build Lazy Scroll SDK"
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    timeout-minutes: 55

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check spotless
        id: spotless_check
        continue-on-error: true
        run: ./gradlew --init-script gradle/init.gradle.kts spotlessCheck --no-configuration-cache

      - name: Apply spotless
        id: spotless_apply
        if: steps.spotless_check.outcome == 'failure' && github.event_name == 'pull_request' && ${{ !cancelled() }}
        run: |
          ./gradlew --init-script gradle/init.gradle.kts spotlessApply --no-configuration-cache

      - name: Push new spotlessed file if available
        uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.spotless_apply.outcome == 'success'
        with:
          file_pattern: '*/*.kt'
          disable_globbing: true
          commit_message: "🤖 Apply spotless"

      - name: Dump GitHub Actions context
        run: |
          echo "Dumping context for debugging"
          env

      - name: Run build
        run: ./gradlew :app:assemble :LazyScrollSdk:assemble


  instrumented_test:
    runs-on: ubuntu-latest
    timeout-minutes: 55
    strategy:
      matrix:
        api-level: [21, 33]

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          disk-size: 6000M
          heap-size: 600M
          avd-name: test-${{ matrix.api-level }}
          script: echo "Generated AVD snapshot for caching."

      - name: Build projects and run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          disable-animations: true
          avd-name: test-${{ matrix.api-level }}
          disk-size: 6000M
          heap-size: 600M
          script: |
            /usr/local/lib/android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages -u | grep starlight.jaehwa.aboutsubnetmask* | cut -d':' -f2 | tr '\r' ' ' | xargs -r -n1 -t adb uninstall; ./gradlew :app:connectedDebugAndroidTest;

      - name: Upload test reports
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'
